### ISSUE TITLE
xapp-sn-watcher crashes on Cinnamon with glib2 version 2.76.0 

### ISSUE THREAD

**Issue by NoXPhasma** [linuxmint/xapp#165]
Distribution: Arch Linux
xapp version: 2.4.2
Cinnamon version: 5.6.7

Since the update to `glib2` version 2.76.0 on Arch Linux, `xapp-sn-watcher` crashes with a segmentation fault when I click on the icon of specific applications (Discord, Gajim), which offer a menu, in the Xapp Status Applet. Downgrading `glib2` to 2.74.6 fixes the issue.

**Comment by ikaikahub** [comment]
Same here. Occasionally when I click a tray icon they'll disappear and reappear a couple times, then will be functional
Segmentation faults for `xapp-sn-watcher` regarding `libgdk-3.so.0.2405.32` in dmesg
The problem is intermittent but has happened a couple times today

Arch Linux
gtk3: 3.24.37
xapp: 2.4.2
Cinnamon: 5.6.7

**Comment by SapphirusBeryl** [comment]
Issue of which is occurring is a memory safety issue exposed by a change made by glib2 switching to malloc from their own memory allocator.

Various other packages with memory safety issues are being exposed by upstream changes to glib2:
https://lore.kernel.org/distributions/87pm97325m.fsf@gentoo.org/T/
